export const RTL_PRACTICE_CONSTANTS = {
  MAIN_HEADING: 'React Testing Library Practice',
  COUNTER_LABEL: 'Count: ',
  INCREMENT_BUTTON: 'Increment',
  DECREMENT_BUTTON: 'Decrement',
  LOGIN_FORM_TITLE: 'Login Form',
  USERNAME_LABEL: 'Username',
  USERNAME_PLACEHOLDER: 'Enter username',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter password',
  LOGIN_BUTTON: 'Login',
  EMPTY_FIELDS_ERROR: 'Please fill all fields',
  LOGIN_SUCCESS: 'Login successful',
  USER_LIST_TITLE: 'User List',
  LOADING_USERS: 'Loading users...',
  DEFAULT_USERS: ['Dheemanth', 'Rahul', 'Priya'],
  DEFAULT_ASYNC_DELAY: 300,
  DEFAULT_INITIAL_COUNT: 0,
};
